// Generated by CoffeeScript 1.11.1
module.exports = function(app) {
  var Page, PageApp, Promise, React, ReactDOMServer, router;
  router = require('express').Router();
  Promise = require('bluebird');
  Page = require('../models/page')(app);
  React = require('react');
  ReactDOMServer = require('react-dom/server');
  PageApp = require('../components/pageapp.jsx');
  return router.get('/', function(req, res) {
    var id, newPages, updatedPages;
    id = req.query.id;
    if (id != null) {
      return new Page({
        'id': id
      }).fetch().then(function(page) {
        if (page != null) {
          return res.render('page', {
            page: page,
            pageapp: ReactDOMServer.renderToString(React.createElement(PageApp, {
              title: page.get("name"),
              content: page.get("content"),
              pageId: page.id
            }))
          });
        } else {
          return res.redirect('/page/new');
        }
      });
    } else {
      updatedPages = [];
      newPages = [];
      return Promise.all([
        Page.query((function(_this) {
          return function(qb) {
            return qb.orderBy('updated_at', 'desc').limit(5);
          };
        })(this)).fetchAll().then((function(_this) {
          return function(updatedPages) {
            return _this.updatedPages = updatedPages;
          };
        })(this)), Page.query((function(_this) {
          return function(qb) {
            return qb.orderBy('created_at', 'desc').limit(5);
          };
        })(this)).fetchAll().then((function(_this) {
          return function(newPages) {
            return _this.newPages = newPages;
          };
        })(this))
      ]).then((function(_this) {
        return function() {
          return res.render('index', {
            updatedPages: _this.updatedPages.models,
            newPages: _this.newPages.models
          });
        };
      })(this));
    }
  });
};
